module.exports = {
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'intro', // This references the id in intro.md
      label: 'Introduction',
    },
    {
      type: 'category',
      label: 'Fynix Prompt Library',
      items: [
        'prompt-library/memory-match',
        'prompt-library/api-boilerplate',
        'prompt-library/complex-sql',
        'prompt-library/optimize-mongodb',
        'prompt-library/caching-redis',
        'prompt-library/debug-sentry',
        'prompt-library/code-quality-sonarqube',
        'prompt-library/unit-tests-backend',
        'prompt-library/unit-tests-frontend',
        'prompt-library/react-components',
        'prompt-library/react-styling',
        'prompt-library/react-state',
        'prompt-library/frontend-performance',
        'prompt-library/auth-authorization',
        'prompt-library/jenkins-cicd',
        'prompt-library/logs-metrics',
        'prompt-library/third-party-apis',
        'prompt-library/async-node',
        'prompt-library/concurrency-asyncio',
        'prompt-library/docker-harbor',
        'prompt-library/input-validation',
        'prompt-library/complete',
        'prompt-library/fix',
        'prompt-library/translate',
        'prompt-library/new-project-scaffolding',
        'prompt-library/test',
        'prompt-library/doc-diagram-explain',
        'prompt-library/mentions',
        'prompt-library/terminal',
      ],
    },
  ],
};
